services:
  - type: web
    name: lecture-helper-backend
    env: python
    buildCommand: |
      pip install -r requirements.txt
      mkdir -p /opt/render/project/src/data/embeddings
      cp -r CS410Transcripts /opt/render/project/src/data/
      cp -r data/embeddings/* /opt/render/project/src/data/embeddings/
    startCommand: gunicorn app:app
    envVars:
      - key: OPEN_AI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.9.0
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1

    buildFilter:
      paths:
        - backend/**
      ignoredPaths:
        - frontend/** 