services:
  - type: web
    name: lecture-helper-backend
    env: python
    buildCommand: |
      {
        echo "=== Starting Build Process ===" || true
        echo "Python version:" || true
        python --version || true
        echo "Current directory:" || true
        pwd || true
        echo "Directory contents:" || true
        ls -la || true
        echo "=== Installing Dependencies ===" || true
        python -m pip install --upgrade pip || true
        pip install -r requirements.txt || { echo "Failed to install requirements"; exit 1; }
        echo "=== Creating Directories ===" || true
        mkdir -p /opt/render/project/src/data/embeddings || true
        mkdir -p /opt/render/project/src/data/CS410Transcripts/vtt || true
        echo "=== Directory Creation Status ===" || true
        ls -la /opt/render/project/src/ || true
        echo "=== Copying Files ===" || true
        cp -rv * /opt/render/project/src/ 2>&1 || { echo "Failed to copy files: $?"; exit 1; }
        echo "=== Final Directory Structure ===" || true
        ls -la /opt/render/project/src/ || true
        echo "=== Verifying Setup ===" || true
        PYTHONPATH=/opt/render/project/src python -c "from app import create_app; print('Importing app...'); app=create_app(); print('App created successfully')" 2>&1 || { echo "Failed to create app: $?"; exit 1; }
      } 2>&1 | tee /opt/render/project/src/build.log
    startCommand: |
      {
        echo "Starting application..." || true
        python -c "import sys; print(f'Python version: {sys.version}')" || true
        echo "Environment variables set:" || true
        env | grep -v "KEY" || true
        echo "Current directory structure:" || true
        ls -R /opt/render/project/src/ || true
        PYTHONPATH=/opt/render/project/src gunicorn --workers 4 --timeout 120 'app:create_app()' --log-level debug --capture-output --enable-stdio-inheritance
      } 2>&1 | tee /opt/render/project/src/start.log
    envVars:
      - key: OPEN_AI_API_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DATA_DIR
        value: /opt/render/project/src/data/embeddings
      - key: VTT_DIRECTORY
        value: /opt/render/project/src/data/CS410Transcripts/vtt
      - key: TXT_DIRECTORY
        value: /opt/render/project/src/data/CS410Transcripts/txt
      - key: RENDER_PROJECT_DIR
        value: /opt/render/project/src
    healthCheckPath: /api/health
    autoDeploy: true
    disk:
      name: data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    buildFilter:
      paths:
        - backend/**
      ignoredPaths:
        - frontend/** 